FROM node:20-bullseye-slim@sha256:f25986842968667c16e5ae7408817cb9b23ee9b3d5cf46ed2be3b171110fa294

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG NODE_OPTIONS
ARG NODE_EXTRA_CA_CERTS

WORKDIR /app

COPY package*.json ./

ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}
ENV NO_PROXY=${NO_PROXY}
ENV NODE_OPTIONS=${NODE_OPTIONS}
ENV NODE_EXTRA_CA_CERTS=${NODE_EXTRA_CA_CERTS}

RUN echo "HTTP_PROXY=$HTTP_PROXY"
RUN echo "HTTPS_PROXY=$HTTPS_PROXY"
RUN echo "NO_PROXY=$NO_PROXY"
RUN echo "NODE_OPTIONS=$NODE_OPTIONS"
RUN echo "NODE_EXTRA_CA_CERTS=$NODE_EXTRA_CA_CERTS"

RUN npm ci --strict-peer-deps

COPY layouts layouts
COPY pages pages
COPY public public
COPY server server
COPY app.vue nuxt.config.ts tsconfig.json ./

ENV HOST_API=http://eudi-verifier
RUN npm run build
RUN npm prune --omit=dev

EXPOSE 3002

CMD ["node", ".output/server/index.mjs"]
