= Använda WSL Ubuntu 24 som utvecklingsmiljö

== Ta bort Podman

Kontrollera om Podman är installerat:

[source,bash]
----
apt list --installed | grep podman
----

Om det är installerat, ta bort det:

[source,bash]
----
sudo apt remove podman
----

Öppna `.zshrc`-filen:

[source,bash]
----
vi ~/config/zsh/.zshrc
----

Kommentera ut raden som exporterar `DOCKER_HOST`:

[source,bash]
----
# export DOCKER_HOST=unix:///run/user/"${USER_UID}"/podman/podman.sock
----

Öppna alias-filen och ta bort eventuell Podman-relaterad alias:

[source,bash]
----
vi ~/.config/zsh/.aliases
----

== Installera Docker

Följ installationsguiden på Dockers officiella dokumentation:
https://docs.docker.com/engine/install/ubuntu/[Installera Docker på Ubuntu]

Lägg till Dockers GPG-nyckel via proxy:

[source,bash]
----
sudo curl \
    -fsSL https://download.docker.com/linux/ubuntu/gpg \
    -o /etc/apt/keyrings/docker.asc \
    -x http://proxy.digg.se:8080
----

Obs: Kom ihåg att när du curlar behöver du använda digg-proxyn!

== Konfigurera Docker med Proxy

Skapa nödvändig katalog:

[source,bash]
----
sudo mkdir -p /etc/systemd/system/docker.service.d/
----

Skapa och redigera proxykonfigurationen:

[source,bash]
----
sudo vi /etc/systemd/system/docker.service.d/http-proxy.conf
----

Klistra in följande innehåll:

[source,ini]
----
[Service]
Environment="HTTP_PROXY=http://proxy.digg.se:8080/"
Environment="HTTPS_PROXY=http://proxy.digg.se:8080/"
Environment="NO_PROXY=*.digg.se,*.sgit.,localhost,127.0.0.1"
----

Starta om Docker för att tillämpa ändringarna:

[source,bash]
----
sudo systemctl daemon-reexec
sudo systemctl daemon-reload
sudo systemctl restart docker
----

Bekräfta att proxyvariablerna är korrekt laddade:

[source,bash]
----
sudo systemctl show --property=Environment docker
----

Testa funktionaliteten genom att dra en skyddad container:

[source,bash]
----
docker pull ghcr.io/swedenconnect/tsl-provider:latest
----

== Konfigurera Diggs Docker-registry

För att förbättra tillgängligheten till interna registries,
konfigurera Docker att använda Diggs mirror.

Redigera `daemon.json`:

[source,bash]
----
sudo vi /etc/docker/daemon.json
----

Lägg in följande konfiguration:

[source,json]
----
{
  "registry-mirrors": ["https://registry.digg.se:5050"],
  "dns": ["10.61.16.11"],
  "dns-search": ["digg.se"],
  "proxies": {
    "http-proxy": "http://proxy.digg.se:8080",
    "https-proxy": "http://proxy.digg.se:8080",
    "no-proxy": "*.test.example.com,.example.org,127.0.0.0/8,registry.digg.se"
  }
}
----

Starta om Docker-demonen för att tillämpa:

[source,bash]
----
sudo systemctl daemon-reexec
sudo systemctl daemon-reload
sudo systemctl restart docker
----

== Konfigurera hosts-filen
Editera din hosts fil:
[source,bash]
----
sudo vi /etc/hosts
----
Ändra från `generateHosts = True` till `generateHosts = False`:
[source,ini]
----
[network]
generateHosts = False
----

== Starta dina Docker-tjänster

Starta upp alla tjänster i bakgrunden:

[source,bash]
----
docker compose up -d
----

== Installera Chrome

Installera Chromium:

[source,bash]
----
sudo apt install chromium-browser
----

Starta Chromium med proxykonfiguration:

[source,bash]
----
chromium-browser \
    --proxy-server='http://proxy.digg.se:8080' \
    --proxy-bypass-list='.dunder.loc,.digg.se,.dev.swedenconnect.se'
----
